### PR TITLE
FibSUM.cpp

### PR DESCRIPTION
**Pull request by CodeLogist**
This one is with Better Space and Time complexity with not extra variable space or Vector. Please have a Look

### CODE REVIEW

**Comment by me-ydv-5** [comment]
That's utterly wrong. Read the problem statement again.

**Comment by me-ydv-5** [comment]
I believe you copied the code from [here](https://github.com/kolaveridi/interviewbit-solutions/blob/master/Sum%20Of%20Fibonacci%20Numbers.cpp). I would not encourage copying and making pull requests, but if @royalpranjal doesn't have any problem, then your solution is good to go except changing 'tahn' to 'than' in [this](https://github.com/royalpranjal/Interview-Bit/pull/20/commits/28b4fc0cb73e514213cea2d176681b360009501c#diff-3e5996f30f6c29faaf3b5a6cff6bb2a3R12) line. The OP has this mistake in his code which reminded me of the same when I saw your code.

**Comment by CodeLogist** [comment]
No absolutely not.. I too support git family standards and would never go for copying. Actually the same question was tough by one of my mentor so I did it that way. And about the mistake in 'tahn' that may by my typo mistake... I'll make it correct thanks for seeing that

**Comment by royalpranjal** [comment]
The code looks fine but it doesn't follow the InterviewBit function template. Can you update the snippet according to the InterviewBit norm ?

**Comment by CodeLogist** [comment]
The interviewBit code panel and online judge also accepted it so i think it does follow the function template. If it my code really needs some changes then, can make it too, theirs no prob at all.

**Pull request merged**
